openapi: 3.0.0
info:
    title: Sample API
    description: A sample API to demonstrate OpenAPI documentation.
    version: 1.0.0
servers:
    - url: http://localhost:8080
      description: Local development server

paths:
    /greet/{name}:
        get:
            summary: Greet a user by name
            description: Returns a greeting message with the provided name.
            parameters:
                - in: path
                  name: name
                  required: true
                  schema:
                      type: string
                  description: Name of the user to greet
            responses:
                '200':
                    description: Successful greeting
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Hello, John!"
                '400':
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components:
    schemas:
        ErrorResponse:
            type: object
            properties:
                errorCode:
                    type: string
                message:
                    type: string
            example:
                errorCode: "400"
                message: "Invalid name provided."
